controller_list:
  - name: fake_arm_controller
    joints:
      - m1n6s300_joint_1
      - m1n6s300_joint_2
      - m1n6s300_joint_3
      - m1n6s300_joint_4
      - m1n6s300_joint_5
      - m1n6s300_joint_6